site_name: Mobile Network Capacity Model
nav:
  - Home: index.md
  - Getting started: "user-guide/getting-started.md"
  - Input data: "input-data.md"
  - Capacity Checker: "models-description/capacity-for-pois-calculation.md"
  - Link Budget Model: "models-description/rmalos-calculation.md"
  - Network capacity Model: "models-description/capacity-calculation.md"
  - License: license.md
theme: readthedocs