site_name: Mobile Network Capacity Model
nav:
  - Home: index.md
  - Getting started: "user-guide/getting-started.md"
  - Preparing your input data: "input-data.md"
  - Network Capacity Model: "models-description/capacity-for-pois-calculation.md"
  - Link Budget Model: "models-description/rmalos-calculation.md"
  - Functions documentation: "models-description/functions-documentation.md"
  - License: license.md
theme: readthedocs